[package]
name = "dorfromantik_remake"
version = "0.1.0"
edition = "2021"

[dependencies]
macroquad = "0.4"
rayon = "1.8"
rand = "0.8"

[[bin]]
name = "simulator"
path = "bin/simulator.rs"

[[bin]]
name = "rl_benchmark"
path = "bin/rl_benchmark.rs"

[[bin]]
name = "train"
path = "bin/train.rs"

[[bin]]
name = "debug_seed"
path = "bin/debug_seed.rs"
